### ISSUE TITLE
Exercise 1.6

### ISSUE THREAD

**Issue by laz0rde** [sgignoux/sicp-solutions.net#18]
For some reason, it doesn't go into an infinite loop for me, ( I use the Pretty-big interpreter in DrRacket)
and the result is almost the same except for the natural numbers that have a natural square root, s.t (sqrt 4) 
with normal if (sqrt 4) gives 2.0000xxxxxx which x's represent some garbage of numbers
but with the If procedure, it produces the natural number 2 w/o any fractions

**Comment by sgignoux** [comment]
Are you using the `sqrt-iter` function that is defined in the example? I am using DrRacket also and I reproduce the infinite loop. Here is what I run:

```
#lang racket

(define (new-if predicate then-clause else-clause)
  (cond (predicate then-clause)
        (else else-clause)))

(define (average x y) (/ (+ x y) 2))

(define (square x) (* x x))

(define (improve guess x) (average guess (/ x guess)))

(define (good-enough? guess x)
(< (abs (- (square guess) x)) 0.001))


(define (sqrt-iter guess x)
  (new-if (good-enough? guess x)
          guess
          (sqrt-iter (improve guess x) x)))


(sqrt-iter 4 1)  ; Infinite loop
```
