### ISSUE TITLE
Exercise 1.14 Typo

### ISSUE THREAD

**Issue by maxwellrherrmann** [sgignoux/sicp-solutions.net#21]
Towards the end of the solution for 1.14 (below the text "by continuing to apply the formulas") it is stated that the summands should be:

T(n-10i,1) for T(n,3)
T(n-25i,1) for T(n,4)
T(n-50i, 1) for T(n,5)

But it seems it should be:

T(n-10i,2) for T(n,3)
T(n-25i,3) for T(n,4)
T(n-50i,4) for T(n,5)

**Comment by sgignoux** [comment]
Thanks a lot, I have fixed it.
