### ISSUE TITLE
Typo in solution 1.14

### ISSUE THREAD

**Issue by seaseao** [sgignoux/sicp-solutions.net#4]
Hi, thank you for making your solutions and work available. It is nice having your insight available as I work through the wizard book!

In your solution for 1.14 you have a slight typo in the below section

```
Let's break it down:

- There are 4 green nodes for `(c x 2)` corresponding to how many time you can subtract a dime from 12, plus one.
- Then for each of the green node, there is the option of using only dime, which is the case that we looked at first.

```
You say dime, but in the example you are showing nickels.

**Comment by sgignoux** [comment]
Thanks @ProducerMatt , this is fixed
