### ISSUE TITLE
Ex 1.13 - concluding statement.

### ISSUE THREAD

**Issue by evansendra** [sgignoux/sicp-solutions.net#7]
[Your solution to ex 1.13](https://codology.net/post/sicp-solution-exercise-1-13/) helped me a lot to understand it; thank you.

In your concluding statement

> This show that `φ^n/√5` will never be further away from the value of `Fib(n)` than 1

I would change this to

> This shows that `φ^n/√5` will never be further away from the value of `Fib(n)` than 1/2

Since the previous statement bounds the value of `φ^n/√5` to `Fib(n) +/- 1/2`

**Comment by jes** [comment]
In fact it can never be as far away as 1/2, because the previous statements bound is "<" rather than "<=".

**Comment by sgignoux** [comment]
Thanks a lot! this is fixed.
